### PR TITLE
Log api calls

### LINKED ISSUE #66: Log API calls.

### PR DESCRIPTION
**Pull request by lucasmpb**
Closes #66.

### CODE REVIEW

**Comment by lindavs** [comment]
@lucasmpb what needs to happen to close this and https://github.com/packethost/staff-portal/pull/2753?

**Comment by lucasmpb** [comment]
@mustela @dkenzox could you review and merge? Thanks!

**Comment by philipcristiano** [comment]
Is this still relevant? It's currently the oldest PR in the ord.

**Comment by philipcristiano** [comment]
:partyenzo:

**Pull request merged**
